version: 1.0.{build}

install:
  - ps: .\install-mongo-on-appveyor.ps1
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  
before_build:
  - nuget restore src/tgLibraries_2010.sln

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - src/packages -> **\packages.config   

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: x64

configuration: Debug
  
build:
  project: src/tgLibraries_2010.sln
  verbosity: Minimal 
  publish_nuget: true
  
after_test: 
  - c:\projects\libraries\cover.bat
  - pip install codecov
  - codecov -f "c:\projects\libraries\tglibraries-coverage.xml" -X gcov  
